env:
  TERM: xterm-24bit

window:
  padding:
    x: 2
    y: 2
  decorations: none
  startup_mode: Maximized
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    # family: Droid Sans Mono for Powerline Plus Nerd File Types Mono
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    #family: Droid Sans Mono for Powerline Plus Nerd File Types Mono
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    #family: Droid Sans Mono for Powerline Plus Nerd File Types Mono
    family: FiraCode Nerd Font Mono
    style: Italic
  bold_italic:
    #family: Droid Sans Mono for Powerline Plus Nerd File Types Mono
    family: FiraCode Nerd Font Mono
    style: Bold Italic
  size: 5.5

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

bell:
  animation: EaseOutExpo
  duration: 100
  color: '#ffffff'


selection:
  save_to_clipboard: false


cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: zsh
  args:
    - --login

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
